### ISSUE TITLE
build-yocto-new: Create non-root user "build"

### ISSUE THREAD

**Issue by gmacario** [gmacario/easy-build#211]
And set as default USER and WORKDIR

**Comment by gunnarx** [comment]
What does this ticket mean? "user build" (I am just curious)
I can of course see what you did when you close it also :)

**Comment by gmacario** [comment]
@gunnarx: The ticket is to create a non-root user to perform the build, otherwise bitbake will complain

**Comment by gmacario** [comment]
Close via cf44664069b2dfc173de0280b076fe76a56bc9d4
