### ISSUE TITLE
build-openwrt: Extend to build LEDE

### ISSUE THREAD

**Issue by gmacario** [gmacario/easy-build#236]
See https://www.lede-project.org/

**Comment by iayanpahwa** [comment]
+1

**Comment by gmacario** [comment]
@iayanpahwa, @jeremiah: I am currently not doing any developments based on LEDE, but will definitely appreciate any PR on this subject 😉

**Comment by gmacario** [comment]
OpenWrt and LEDE have merged a while ago, therefore I do not think this issue is still relevant.
