### ISSUE TITLE
How to change the configuration files?

### ISSUE THREAD

**Issue by naveen230** [gmacario/easy-build#265]
I can't change the variables in local.conf and bblayers.conf files.I tried using vi vim and nano commands.Most importantly I wanted to add meta-mender (mender.io) layers and change the machine to Raspberrypi3.Is there a way to do that?

Thanks

**Comment by naveen230** [comment]
the solution is to install vim in the docker container
sudo apt-get update
sudo apt-get install vim

**Comment by gmacario** [comment]
Hello @naveen230 ,

Not sure which Docker image of the easy-build project you are referring to.

The general idea is that the image should not contain local.conf and bblayers.conf which may be mounted from a volume, or even reside on the Docker host, therefore they can be edited with any editors installed on the host itself.

Honestly I do not see the need for installing an editor inside the container.

Please correct me if I am wrong

**Comment by gmacario** [comment]
No feedbacks received, closing
