### ISSUE TITLE
`apt-get update` and `apt-get install` should probably be in the same line

### ISSUE THREAD

**Issue by LittleCVR** [gmacario/easy-build#268]
According to this article: https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#run `apt-get update` and `apt-get install` should be in the same line. Otherwise, a caching problem may occur.

So are they being separated intentionally here?

**Comment by gmacario** [comment]
HI @LittleCVR ,

Thanks for your remark, and pointing me out to this Docker best practice.

> So are they being separated intentionally here?

I believe it is so just because I wrote the Dockerfile without knowing this best practice yet... 

Anyway PR are welcome :wink:
