### ISSUE TITLE
build-yocto-genivi is deprecated and out for adoption

### ISSUE THREAD

**Issue by gmacario** [gmacario/easy-build#271]
I am no longer actively involved in [GENIVI Alliance](http://www.genivi.org) and consequently I no longer use and cannot test the gmacario/build-yocto-genivi Docker image.

If anybody (@gunnarx, hint, hint...) wants to adopt this subproject, just let me know here, so I can remove this subdirectory from the gmacario/easy-build project and concentrate on the other images, most notably build-yocto.

**Comment by gmacario** [comment]
@gunnarx I have not received any more feedbacks by you, therefore I assume I can safely remove folder `build-yocto-genivi/` from my repository

**Comment by mirzak** [comment]
Hi @gmacario , I am involved in GENIVI Alliance together with @gunnarx. Gunnar is currently out-of-office so jumping in here.

I believe that it is of interest to keep the directory in your repository. You do not have to maintain/update it, but instead we will make sure to keep it up to date.

**Comment by mirzak** [comment]
Seems I was to late.

**Comment by gunnarx** [comment]
Thanks @mirzak. I already had more discussion with @gmacario. He does not seem to want to keep it here, so it seems maintaining a build container somewhere else is now the easiest approach.

**Comment by gmacario** [comment]
Hi @mirzak, @gunnarx 

> He does not seem to want to keep it here

To clarify: I am no longer actively involved in GENIVI therefore I do not feel I have the time to keep maintaining Docker image `gmacario/build-yocto-genivi`.

This is the main reason why I chose to remove the `build-yocto-genivi` subfolder from <https://github.com/gmacario/easy-build>

On the other hand, I do use and actively maintain Docker image `gmacario/build-yocto`, so if you find it useful you could consider rebasing any Docker image you may need for building GDP and or meta-ivi on it. By the way, last time I tried to build GDP master I realized I could safely build genivi-demo-image using Docker image `gmacario/build-yocto`. 

Hope that helps -- Gianpaolo
